baseURL : https://rosieandcompany.ca/
languageCode : en-us
title : Rosie and Company - Toronto Dog Walking Service
theme : hugo-sodium-theme

taxonomies:
  category: categories
  tag: tags

params:
  social:
    facebook: uicardio
    instagram: uicardio
    twitter: uicardio

  scripts:
    googleanalytics: 
    disqus: 
    
